# Init active learning
train_name: active_learning

# root_dir: "AL"
root_dir: "/media/workstation/Storage/Test/AL"
main_dir: "active_learning_v1_test"
main_data_dir: ../all_train_300
train_dir: full_train

max_steps: 50

# active learning parameters
m: 50
n: 18

# to vary:

# preprocessing
workers: 8
size: 400
reweight_sample: 2000 #-1 #resample limited label images to 1k images with oversampling

# model
model_type: xception
epochs: 50 # max epoch to run
patience: 5 # implement patience to stop training if val doesnt improve
batch_size: 10
batch_multiplier: 10

# loss
loss_type: cross_entropy

# metric 
metric_type: softmax
num_ftr: 1000
num_classes: 5

# optimizer
# optimizer_type: AdamW
# opt_kwargs:
#   lr: 0.01
#   weight_decay: 0.0025

optimizer_type: SGD
opt_kwargs:
  lr: 0.01
  momentum: 0.95
  # weight_decay: 0.0001
  weight_decay: 0.0025

model_kwargs:
  pretrained: True
scheduler_type: CosineAnnealingLR
scheduler_kwargs:
  T_max: 50
  eta_min: 0.0001

# https://www.fast.ai/2018/07/02/adam-weight-decay/#implementing-adamw
# adamw with onecycle
