train_name: dual_xception_test

# RETRAIN
main_data_dir: ../all_train_300
use_train_dir: full_train
main_model_dir: torch_models
workers: 8
size: 400
batch_size: 6
batch_multiplier: 15
reweight_sample: 1
reweight_sample_factor: 0.2

epochs: 50

loss_type: cross_entropy
model_type: dual_xception
metric_type: softmax
num_ftr: 1000
num_classes: 5

optimizer_type: AdamW
opt_kwargs:
  lr: 0.01
  weight_decay: 0.0025

# optimizer_type: SGD
# opt_kwargs:
#   lr: 0.1
#   momentum: 0.95
#   # weight_decay: 0.0001
#   weight_decay: 0.0025

model_kwargs:
  pretrained: True
scheduler_type: CosineAnnealingLR
scheduler_kwargs:
  T_max: 50
  eta_min: 0.0001

# https://www.fast.ai/2018/07/02/adam-weight-decay/#implementing-adamw
# adamw with onecycle
