
# Continue restoration config
cn_config:
  current_step: 0
  main_path: ./torch_DualAL/dual_al_ui
  previous_step_path: ./torch_DualAL/dual_al_ui/step_001

# Active Learning Config
al_config:
  train_name: dual_active_learning
  style: ui # random
  random_state: 123

  # root_dir: "AL"
  root_dir: "./torch_DualAL"
  main_dir: "dual_al_ui" # dual_al_random
  val_n_sample: 500 #500
  max_steps: 25

  # active learning parameters
  m: 200 # 200, start 200,100
  n: 100  # 100, step sampling
  outlier: 0.01

# Model Config:
model_config:
  train_name: new_single_resnext50_imagenet_400

  # RETRAIN
  retrain: 0
  premodel_path: torch_models/new_small_dual_xception_400_v3a_v13/best_qk_model.pth

  load_only: 1
  main_data_dir: ..
  train_dir_list: 
    - new_all_train_400

  main_model_dir: torch_models
  workers: 8
  size: 400
  batch_size: 2
  batch_multiplier: 30
  reweight_sample: 0
  reweight_sample_factor: 2
  single_mode: 1

  epochs: 50
  loss_type: smoothl1loss
  model_type: single_resnext101
  model_kwargs:
    num_ftrs: 1000
    num_classes: 1
    use_init: kaiming
    limit_two: 1
  qk_patience: 10 #10

  optimizer_type: AdamW
  opt_kwargs:
    lr: 0.0002
    weight_decay: 0.000025

  scheduler_type: CosineAnnealingLR
  scheduler_kwargs:
    T_max: 50
    eta_min: 0.0002



