train_name: resnext101_32x8d
main_data_dir: data3
main_model_dir: torch_models
model_type: resnext101_32x8d
metric_type: adacos
num_ftr: 1000
num_classes: 7 
batch_size: 32
epochs: 1000
optimizer_type: AdamW
opt_kwargs:
  lr: 0.001
  weight_decay: 0.025
model_kwargs:
  pretrained: True
scheduler_type: CosineAnnealingLR
scheduler_kwargs:
  T_max: 1000
  eta_min: 0.00001