train_name: xception_d400_v1
# main_data_dir: ../resize_train
main_data_dir: ../all_train_300
use_train_dir: full_train
main_model_dir: torch_models
workers: 14
size: 400
batch_size: 8
batch_multiplier: 8
fix_sample: 10000
fix_sample_val: -1
epochs: 1000

# loss_type: cross_entropy
loss_type: cross_entropy
model_type: xception
metric_type: adacos
num_ftr: 1000
num_classes: 5

optimizer_type: AdamW
opt_kwargs:
  lr: 0.0005
  weight_decay: 0.0025
# optimizer_type: SGD
# opt_kwargs:
#   lr: 0.0001
#   momentum: 0.5
#   weight_decay: 0.025

model_kwargs:
  pretrained: True
scheduler_type: CosineAnnealingLR
scheduler_kwargs:
  T_max: 1000
  eta_min: 0.00001

# https://www.fast.ai/2018/07/02/adam-weight-decay/#implementing-adamw
# adamw with onecycle
