train_name: xception_sgd_test_d500_adamw

# RETRAIN
retrain: 0
# premodel_path: ./torch_models/xception_d400_force_v1_v09/best_avg_acc_model.pth
# premetric_path: ./torch_models/xception_d400_force_v1_v09/best_avg_acc_metric_fc.pth

# main_data_dir: ../resize_train
main_data_dir: ../all_train_300
use_train_dir: full_train
main_model_dir: torch_models
workers: 8
size: 400
batch_size: 12
batch_multiplier: 15
force_random_sample: 2000
fix_sample: 10000
fix_sample_val: 2000
epochs: 50

loss_type: cross_entropy
model_type: xception
metric_type: softmax
num_ftr: 1000
num_classes: 5

optimizer_type: AdamW
opt_kwargs:
  lr: 0.01
  weight_decay: 0.0025

# optimizer_type: SGD
# opt_kwargs:
#   lr: 0.1
#   momentum: 0.95
#   # weight_decay: 0.0001
#   weight_decay: 0.0025

model_kwargs:
  pretrained: True
scheduler_type: CosineAnnealingLR
scheduler_kwargs:
  T_max: 50
  eta_min: 0.0001

# https://www.fast.ai/2018/07/02/adam-weight-decay/#implementing-adamw
# adamw with onecycle
