train_name: resnet34_v4
main_data_dir: data3
main_model_dir: torch_models
model_type: resnet34
metric_type: adacos
num_ftr: 1000
num_classes: 7 
batch_size: 64
epochs: 1000
optimizer_type: AdamW
opt_kwargs:
  lr: 0.001
  weight_decay: 0.025
model_kwargs:
  pretrained: True
scheduler_type: CosineAnnealingLR
scheduler_kwargs:
  T_max: 1000
  eta_min: 0.00001

# https://www.fast.ai/2018/07/02/adam-weight-decay/#implementing-adamw
# adamw with onecycle