train_name: resnet18_test
main_data_dir: ../all_train
main_model_dir: torch_models
model_type: resnet18
metric_type: adacos
num_ftr: 1000
num_classes: 5 
batch_size: 32
epochs: 10
optimizer_type: AdamW
opt_kwargs:
  lr: 0.001
  weight_decay: 0.025
model_kwargs:
  pretrained: True
scheduler_type: CosineAnnealingLR
scheduler_kwargs:
  T_max: 1000
  eta_min: 0.00001

# https://www.fast.ai/2018/07/02/adam-weight-decay/#implementing-adamw
# adamw with onecycle
